### ISSUE TITLE
sample_train.tar.gz 和sample_test.tar.gz解压失败

### ISSUE THREAD

**Issue by Xjh0327** [mrchor/FDN#2]
您好，我在尝试运行aliccp的run.sh时，报错sample_train.tar.gz 和sample_test.tar.gz解压失败，进入下载数据的链接中查看，显示AccessDenied & Request has expired，能否更新一下下载的链接以便参考？非常感谢！

**Comment by mrchor** [comment]
可以尝试一下手动下载并解压~
















在 2023-11-29 10:57:41，"Xu Jiahui" ***@***.***> 写道：

您好，我在尝试运行aliccp的run.sh时，报错sample_train.tar.gz 和sample_test.tar.gz解压失败，进入下载数据的链接中查看，显示AccessDenied & Request has expired，能否更新一下下载的链接以便参考？非常感谢！

**Comment by Xjh0327** [comment]
好的，非常感谢！
